services:
  catalogmanagermultilingualadapter.hooks.datacontainer:
    class: Alnv\ContaoCatalogManagerMultilingualAdapterBundle\Hooks\DataContainer
    public: true
  catalogmanagermultilingualadapter.datacontainer.catalogfield:
    class: Alnv\ContaoCatalogManagerMultilingualAdapterBundle\DataContainer\CatalogField
    public: true
  catalogmanagermultilingualadapter.hooks.catalogwizard:
    class: Alnv\ContaoCatalogManagerMultilingualAdapterBundle\Hooks\CatalogWizard
    public: true